init:
  - git config --global core.autocrlf input
  
branches:
  only:
  - master

before_build:
  - start /d "C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator" /wait WAStorageEmulator.exe start
  
cache:
   - C:\Users\appveyor\AppData\Local\NuGet\Cache
   - C:\projects\journalist\packages

build_script:
  - cmd: build.bat

test: off

version: 0.0.1.{build}

artifacts:
  - path: out
    name: out
